version: '3.2'
services:

  apiserver:
      build:
          context: modules/device-simulator-backend
          dockerfile: Dockerfile.zcsimserver
      environment: &env
          - ZCSIM_ENV=localtesting_fridge
      ports:
          - "6000:5000"
      depends_on:
          - celeryworker
          - redis

  celeryworker:
      environment: *env
      build:
          context: modules/device-simulator-backend
          dockerfile: Dockerfile.zcsimworker
      depends_on:
          - redis

  celerybeat:
      environment: *env
      build:
          context: modules/device-simulator-backend
          dockerfile: Dockerfile.zcsimbeat
      depends_on:
          - redis

  server: &common_mount
      depends_on:
          - redis
      build:
          context: modules/zconnect-django-demo
          dockerfile: deploy/Dockerfile.composelocal
      volumes:
          - type: bind
            target: /django/django_demo
            source: ./modules/zconnect-django-demo/django_demo
            read_only: true
          - type: bind
            target: /django/apps/zconnect-django
            source: ./modules/zconnect-django-demo/apps/zconnect-django
            read_only: true
          - type: bind
            target: /django/configs
            source: ./configs
            read_only: true
          - type: bind
            target: /django/manage.py
            source: ./modules/zconnect-django-demo/manage.py
            read_only: true
          - target: /django/run/
            source: ./modules/zconnect-django-demo/run
            type: bind
          - target: /django/keys
            source: ./modules/zconnect-django-demo/keys
            type: bind
      ports:
          - "8981:8981"
      environment:
          DJANGO_SETTINGS_MODULE: django_demo.settings.composelocal
          PYTHONPATH: "/django:/django/apps/zconnect-django"
          DJANGO_SEED_PROJECT: 1
          DJANGO_SEED_REQUIRES_SETUP: 1
      command:
          # server
          # ["python3", "/django/manage.py", "runserver", "0.0.0.0:8981"]
          # ["uwsgi", "--ini", "/django/configs/uwsgi-development.ini"]
          - "sh"
          - "-c"
          - "python3 /django/manage.py migrate ; uwsgi --ini /django/configs/uwsgi.ini"

  celeryworker:
      <<: *common_mount
      ports: []
      command:
          # celery worker
          - "celery"
          - "-A"
          - "django_demo"
          - "worker"
          - "-l"
          - "info"

  celerybeat:
      <<: *common_mount
      ports: []
      command:
          # celery worker
          - "celery"
          - "-A"
          - "django_demo"
          - "beat"
          - "--loglevel=DEBUG"
          - "-s"
          - "/tmp/celerybeat-schedule"
          - "--pidfile=/tmp/celerybeat.pid"

  listener:
      <<: *common_mount
      ports: []
      command:
          # message listener
          - "uwsgi"
          - "--ini"
          - "/django/configs/uwsgi-listener.ini"

  redis:
    image: redis:latest

  vernemq:
    image: erlio/docker-vernemq
    # build:
    #   context: ./ibm-iot-emulator/vernemq
    # volumes:
    #   - "./ibm-iot-emulator/vernemq/files/config/:/etc/vernemq/"
    # env_file:
    #   - "./ibm-iot-emulator/vernemq/files/vmq.vars"
    environment:
      WAIT_FOR_ERLANG: 25
    volumes:
      - "./modules/ibm-iot-emulator/vernemq/files/config/:/etc/vernemq/"
    depends_on:
      - hooks
      # - mongo-setup
    ports:
      - "1883:1883"
      - "9001:8080"

  hooks:
    build:
      context: ./modules/ibm-iot-emulator/overlock-mqtt-auth
      dockerfile: Dockerfile.vernemq
    ports:
      - "5000:5000"
    environment:
      MQTT_HOST: vernemq
      MQTT_PORT: 8080
      HOOK_PORT: 5000

      MONGO_SSL: "false"
      MONGO_APPNAME: webhooks
      # FIXME
      MONGO_DATABASE: zdemoapp
      OVERLOCK_WORKER_PASSWORD: "123456789"

      VMQ_USERNAME: overlock-worker
      VMQ_PASSWORD: "123456789"

  frontend:
    build:
      context: modules/device-simulator-frontend
      dockerfile: Dockerfile-node
    depends_on:
      - apiserver
    ports:
      - "9000:9000"

  web:
    build:
      context: modules/zconnect-demo-web
      dockerfile: Dockerfile-node
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  db_data:
    driver: local
